apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: adservice
  annotations:
    run.googleapis.com/ingress: internal-and-cloud-load-balancing
    run.googleapis.com/launch-stage: BETA
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: '50'
        run.googleapis.com/execution-environment: gen2
        autoscaling.knative.dev/maxScale: '1000'
    spec:
      containerConcurrency: 10
      timeoutSeconds: 600
      containers:
      - image: gcr.io/google-samples/microservices-demo/adservice:v0.3.6
        ports:
        - name: h2c
          containerPort: 9555
        env:
        # - name: DISABLE_STATS
        #   value: "0"
        # - name: DISABLE_TRACING
        #   value: "0"
        # - name: JAEGER_SERVICE_ADDR
        #   value: "jaeger-collector:14268"
        resources:
          limits:
            cpu: 1000m
            memory: 512Mi
  traffic:
  - percent: 100
    latestRevision: true
