apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: productcatalogservice
  annotations:
    run.googleapis.com/ingress: internal-and-cloud-load-balancing
    run.googleapis.com/launch-stage: BETA
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: '2'
        run.googleapis.com/execution-environment: gen2
        autoscaling.knative.dev/maxScale: '1000'
        run.googleapis.com/cpu-throttling: 'false'
    spec:
      containerConcurrency: 10
      timeoutSeconds: 600
      containers:
      - image: asia-east2-docker.pkg.dev/play-with-anthos-340801/cloudrun-loader/productcatalogservice
        ports:
        - name: h2c
          containerPort: 3550
        env:
        # - name: DISABLE_STATS
        #   value: "0"
        # - name: DISABLE_TRACING
        #   value: "0"
        # - name: DISABLE_PROFILER
        #   value: "0"
        # - name: JAEGER_SERVICE_ADDR
        #   value: "jaeger-collector:14268"
        resources:
          limits:
            cpu: 1000m
            memory: 512Mi
  traffic:
  - percent: 100
    latestRevision: true
