apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: shippingservice
  annotations:
    run.googleapis.com/ingress: internal-and-cloud-load-balancing
    run.googleapis.com/launch-stage: BETA
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: '2'
        run.googleapis.com/execution-environment: gen2
        autoscaling.knative.dev/maxScale: '1000'
        run.googleapis.com/cpu-throttling: 'false'
    spec:
      containerConcurrency: 10
      timeoutSeconds: 600
      containers:
      - image: ${shippingservice}
        ports:
        - name: h2c
          containerPort: 50051
        env:
        # - name: DISABLE_TRACING
        #   value: "1"
        # - name: DISABLE_PROFILER
        #   value: "1"
        # - name: DISABLE_DEBUGGER
        #   value: "1"
        resources:
          limits:
            cpu: 1000m
            memory: 512Mi
  traffic:
  - percent: 100
    latestRevision: true
