apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apiextensions.k8s.io/v1","kind":"CustomResourceDefinition","metadata":{"annotations":{},"creationTimestamp":"2022-06-15T05:14:19Z","generation":1,"labels":{"addonmanager.kubernetes.io/mode":"Reconcile","cloud-run.operator.run.cloud.google.com/release":"devel","knative.dev/crd-install":"true","operator.knative.dev/release":"v0.23.0-gke.5"},"name":"cloudruns.operator.run.cloud.google.com","resourceVersion":"790","uid":"f17db5fb-2190-4dcb-8404-330c72f2c954"},"spec":{"conversion":{"strategy":"None"},"group":"operator.run.cloud.google.com","names":{"categories":["all","knative"],"kind":"CloudRun","listKind":"CloudRunList","plural":"cloudruns","shortNames":["run","runs"],"singular":"cloudrun"},"scope":"Namespaced","versions":[{"additionalPrinterColumns":[{"jsonPath":".status.conditions[?(@.type=='Ready')].status","name":"Ready","type":"string"},{"jsonPath":".status.conditions[?(@.type=='Ready')].reason","name":"Reason","type":"string"}],"name":"v1alpha1","schema":{"openAPIV3Schema":{"type":"object","x-kubernetes-preserve-unknown-fields":true}},"served":true,"storage":true,"subresources":{"status":{}}}]},"status":{"acceptedNames":{"categories":["all","knative"],"kind":"CloudRun","listKind":"CloudRunList","plural":"cloudruns","shortNames":["run","runs"],"singular":"cloudrun"},"conditions":[{"lastTransitionTime":"2022-06-15T05:14:19Z","message":"no conflicts found","reason":"NoConflicts","status":"True","type":"NamesAccepted"},{"lastTransitionTime":"2022-06-15T05:14:19Z","message":"the initial names have been accepted","reason":"InitialNamesAccepted","status":"True","type":"Established"}],"storedVersions":["v1alpha1"]}}
  creationTimestamp: "2022-06-15T07:55:29Z"
  generation: 1
  labels:
    addonmanager.kubernetes.io/mode: Reconcile
    cloud-run.operator.run.cloud.google.com/release: devel
    knative.dev/crd-install: "true"
    operator.knative.dev/release: v0.23.0-gke.5
  name: cloudruns.operator.run.cloud.google.com
  resourceVersion: "19340"
  uid: 93cc98d3-6aed-4890-ac38-b4e8f3da4c2d
spec:
  conversion:
    strategy: None
  group: operator.run.cloud.google.com
  names:
    categories:
    - all
    - knative
    kind: CloudRun
    listKind: CloudRunList
    plural: cloudruns
    shortNames:
    - run
    - runs
    singular: cloudrun
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - jsonPath: .status.conditions[?(@.type=='Ready')].status
      name: Ready
      type: string
    - jsonPath: .status.conditions[?(@.type=='Ready')].reason
      name: Reason
      type: string
    name: v1alpha1
    schema:
      openAPIV3Schema:
        type: object
        x-kubernetes-preserve-unknown-fields: true
    served: true
    storage: true
    subresources:
      status: {}
status:
  acceptedNames:
    categories:
    - all
    - knative
    kind: CloudRun
    listKind: CloudRunList
    plural: cloudruns
    shortNames:
    - run
    - runs
    singular: cloudrun
  conditions:
  - lastTransitionTime: "2022-06-15T07:55:29Z"
    message: no conflicts found
    reason: NoConflicts
    status: "True"
    type: NamesAccepted
  - lastTransitionTime: "2022-06-15T07:55:29Z"
    message: the initial names have been accepted
    reason: InitialNamesAccepted
    status: "True"
    type: Established
  storedVersions:
  - v1alpha1
