apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: frontend
  annotations:
    run.googleapis.com/ingress: all
    run.googleapis.com/launch-stage: BETA
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: '2'
        run.googleapis.com/execution-environment: gen2
        autoscaling.knative.dev/maxScale: '1000'
    spec:
      containerConcurrency: 10
      timeoutSeconds: 600
      containers:
      - image: asia-east2-docker.pkg.dev/play-with-anthos-340801/cloudrun-loader/frontend
        ports:
        - name: http1
          containerPort: 8080
          # readinessProbe:
          #   initialDelaySeconds: 10
          #   httpGet:
          #     path: "/_healthz"
          #     port: 8080
          #     httpHeaders:
          #     - name: "Cookie"
          #       value: "shop_session-id=x-readiness-probe"
          # livenessProbe:
          #   initialDelaySeconds: 10
          #   httpGet:
          #     path: "/_healthz"
          #     port: 8080
          #     httpHeaders:
          #     - name: "Cookie"
          #       value: "shop_session-id=x-liveness-probe"
        env:
        # - name: PORT
        #   value: "8080"
        - name: PRODUCT_CATALOG_SERVICE_ADDR
          value: "productcatalogservice-vig5qbg5jq-df.a.run.app:443:3550"
        - name: CURRENCY_SERVICE_ADDR
          value: "currencyservice-vig5qbg5jq-df.a.run.app:443:7000"
        - name: CART_SERVICE_ADDR
          value: "cartservice-vig5qbg5jq-df.a.run.app:443:7070"
        - name: RECOMMENDATION_SERVICE_ADDR
          value: "recommendationservice-vig5qbg5jq-df.a.run.app:443:8080"
        - name: SHIPPING_SERVICE_ADDR
          value: "shippingservice-vig5qbg5jq-df.a.run.app:443:50051"
        - name: CHECKOUT_SERVICE_ADDR
          value: "checkoutservice-vig5qbg5jq-df.a.run.app:443:5050"
        - name: AD_SERVICE_ADDR
          value: "adservice-vig5qbg5jq-df.a.run.app:443:9555"
        - name: DISABLE_TRACING
          value: "1"
        - name: DISABLE_PROFILER
          value: "1"
        resources:
          limits:
            cpu: 1000m
            memory: 512Mi
  traffic:
  - percent: 100
    latestRevision: true
